id = "bruno"
name = "Bruno"
version = "0.0.1"
schema_version = 1
authors = ["ebina4yaka <ebina4yaka@protonmail.com>"]
description = "Bruno support"
repository = "https://github.com/ebina4yaka/bruno-zed-extension"
license = "MIT"

[language_servers.bruno-language-server]
name = "Bruno Language Server"
language = "Bruno"

[grammars.bruno]
repository = "https://github.com/Scalamando/tree-sitter-bruno"
rev = "dd27fe0eff8e7f8184dfc91e426b886dc8369c46"
